# Generated by Django 2.1.5 on 2019-05-02 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveSmallIntegerField()),
                ('columns', models.PositiveSmallIntegerField()),
                ('cell_size', models.PositiveSmallIntegerField(default=20, verbose_name='cell size')),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'przeszkody',
            },
        ),
        migrations.CreateModel(
            name='TestBoard',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='opis')),
                ('rows', models.PositiveSmallIntegerField(default=20, verbose_name='rzędy')),
                ('columns', models.PositiveSmallIntegerField(default=20, verbose_name='kolumny')),
                ('cell_size', models.PositiveSmallIntegerField(default=20, verbose_name='rozmiar komórki')),
                ('summary', models.CharField(max_length=200, verbose_name='uwagi')),
                ('board_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obstacles_json', models.CharField(blank=True, max_length=10000, null=True)),
                ('lidar_x', models.PositiveSmallIntegerField(default=0)),
                ('lidar_y', models.PositiveSmallIntegerField(default=0)),
                ('obstacles', models.ManyToManyField(to='main.Obstacle')),
            ],
            options={
                'verbose_name_plural': 'Test Boards',
            },
        ),
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 5, 2, 21, 1, 26, 925679))),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TestBoard', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TestBoard', verbose_name='Test Board')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Test Scenarios',
            },
        ),
    ]
