# Generated by Django 2.1.5 on 2019-05-03 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190502_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTest',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operating_mode', models.CharField(choices=[('1', '1'), ('2', '1/2'), ('4', '1/4'), ('8', '1/8'), ('16', '1/16'), ('32', '1/32')], default='1', max_length=200)),
                ('TestBoard', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TestBoard', verbose_name='Test Board')),
            ],
            options={
                'verbose_name_plural': 'pojedyńczy scenariusz',
            },
        ),
        migrations.RemoveField(
            model_name='testscenario',
            name='TestBoard',
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 26, 46, 936740)),
        ),
    ]
