# Generated by Django 2.1.5 on 2019-05-03 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190503_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletest',
            name='reps',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 17, 57, 16, 150418)),
        ),
    ]
