# Generated by Django 2.1.5 on 2019-05-03 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190503_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletest',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TestBoard', verbose_name='plansza testowa'),
        ),
        migrations.AlterField(
            model_name='singletest',
            name='reps',
            field=models.SmallIntegerField(verbose_name='powtórzenia pomiaru'),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 17, 58, 58, 18512)),
        ),
    ]
