# Generated by Django 2.1.5 on 2019-05-03 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190503_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletest',
            name='reps',
            field=models.PositiveSmallIntegerField(verbose_name='powtórzenia pomiaru'),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 18, 0, 27, 358065)),
        ),
    ]
